### ISSUE TITLE
clone statement doesn't work.

### ISSUE THREAD

**Issue by humank** [imyoungyang/video-streaming#1]
Clone statement will lead to the error due to public key issue.

> git clone git@github.com:imyoungyang/video-streaming.git
> Cloning into 'video-streaming'...
> Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.

**Comment by imyoungyang** [comment]
I think it is solved.
