### ISSUE TITLE
Kinesis Video Streaming using .Net SDK

### ISSUE THREAD

**Issue by harishsune** [imyoungyang/video-streaming#2]
I am trying to develop same application using .Net SDK. but as there in python I don't see any PutMedia() in AmazonKinesisVideoClient class. Could you please here how you figured out this problem?

**Comment by imyoungyang** [comment]
Sorry for my late reply.

You can reference this shell script: https://github.com/imyoungyang/video-streaming/blob/master/putMkvMedia.sh

I compiled a jar file: -jar ./kinesisvideo-java-demo-1.0-SNAPSHOT.jar
In this jar file, it call PutMedia()

Wish it will help you.
